services:
  - type: web
    name: signaling-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js # Assuming your server file is named server.js
    healthCheckPath: /status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
