services:
  - type: web
    name: screen-share-signaling
    env: node
    region: oregon # Choose your preferred region
    plan: free # Use free tier - upgrade as needed
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
    domains:
      - screen-share.onrender.com # Replace with your preferred subdomain

# Networking configuration - ensures WebSockets work properly
routes:
  - type: rewrite
    source: /*
    destination: /
