services:
  - type: web
    name: signaling-server
    env: node
    plan: starter # You can adjust this based on your needs (starter, standard, etc.)
    buildCommand: npm install
    startCommand: node server.js # Assuming your server file is named server.js
    healthCheckPath: /status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    autoDeploy: true
